name: Docker Image CI

# run on merge or push to master
on:
  push:
    branches: [ "master" ]

# will have 2 jobs: one to build and push image to dockerhub, other to pull on ecs and run it as a container
jobs:

  build_and_test:

    runs-on: ubuntu-latest

    steps:

      # checkout code first
      - name: Checkout code
        uses: actions/checkout@v4

      # then login to dockerhub
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # then generate timestamp
      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      # then build and push
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          # List of tags
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hello_ci_cd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hello_ci_cd:${{ steps.timestamp.outputs.timestamp }}
          # Sets the target stage to build
          target: final