name: CI - Test Application

on:
  # only run while pull requested on master branch
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run tests with Docker Compose
      run: docker compose -f compose.test.yml up --abort-on-container-exit --exit-code-from backendtest
      
    - name: Clean up
      if: always()
      run: docker compose -f compose.test.yml down --rmi all