# will create a workflow without containerization
# no issue, since github actions already run in a virtualized environment, so no need to add another layer of containerization

name: CI - Test Application without Containerization
on:
  # only run while pushed or pull requested on master branch
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  # see jobs are independent of each other,
  # ie, they run on different virtual machines
  # can indeed create complex flows using "needs", but that just sets up control flow, not data flow
  # so, here we need to do a single thing: test our code
  # hence only one job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.0'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test